# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --force
      - run: NODE_ENV=production npm run build --if-present
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: 'master'
          folder: 'dist'
          ssh-key: '${{ secrets.SSH_KEY }}'
          clean: false
          repository-name: 'android/android.github.io'
          target-folder: 'analyseOTA'
